### ISSUE TITLE
TinyCss doesnot support @font-face.

### ISSUE THREAD

**Issue by hashMH** [Kozea/tinycss#6]
@font-face in css files gives off ParseError. Please Confirm

**Comment by jdufresne** [comment]
I've noticed this as well. [Bootstrap](http://getbootstrap.com/) makes use of `@font-face`. This can cause lots of reported errors when using tinycss to verify CSS correctness.

**Comment by SimonSapin** [comment]
I don’t have more to add to my comment above.

**Comment by liZe** [comment]
This should be fixed with 100%-tested commit:7ac8bc3. Tests and reviews are welcome!

**Comment by liZe** [comment]
Tests now pass with 2.7, 3.3, 3.4, 3.5, pypy and pypy3, with isort, flake8 and coverage.
